/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>
#include <sys/stat.h> 

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include <glib.h>

#include "tdp_preference.h"

/* use g_access() on win32 */
#if defined(G_OS_WIN32)
#include <glib/gstdio.h>
#else
#define g_access(filename, mode) access((filename), (mode))
#endif

static void get_xdg_home_dir(gchar* strFolder)
{
    const gchar *result;

    result = g_getenv ("XDG_CONFIG_HOME");
    if (result == NULL)
    {
        result = g_get_home_dir();
        /* security issue! */
        snprintf(strFolder, PATH_MAX - 1, "%s/.config/", result);
    }
    else
    {
        /* security issue! */
        strncpy(strFolder, result, PATH_MAX - 1);
    }
    strFolder[PATH_MAX-1] = '\0';
    
    return;
}

void load_perf_config_info(PerferenceInfo *pInfo, const gchar* str_perf_file)
{
    gint len;
    gchar *strtmp;
    GKeyFile * keyfile;
    gchar strFile[PATH_MAX];

    if (NULL != pInfo->compare_edt)
        g_free(pInfo->compare_edt);
    if (NULL != pInfo->three_way_compare_edt)
        g_free(pInfo->three_way_compare_edt);
    if (NULL != pInfo->select_left_item)
        g_free(pInfo->select_left_item);
    if (NULL != pInfo->select_middle_item)
        g_free(pInfo->select_middle_item);
    //memset(pInfo, 0, sizeof(PerferenceInfo));
    
    /* get folder name */
    get_xdg_home_dir(strFile);
    
    len = strlen(strFile);
    if (strFile[len-1] != '/')
    {
        if (len == PATH_MAX - 1)
        {
            g_warning("[load]]XDG_CONFIG_HOME is too long!");
            return;
        }
        
        strFile[len-1] = '/';
        strFile[len] = '\0';
        len++;
    }
    
    /* append file name, security issue. */
    strncpy(strFile + len, str_perf_file, (PATH_MAX - len) - 1);

    /* file is exist? */
    if (0 != g_access(strFile,  R_OK))
    {
        g_warning("[load]Can't access config file: %s", strFile);
        return;
    }
    
    /* read config info */
    keyfile = g_key_file_new();
    if (!g_key_file_load_from_file(keyfile, strFile, G_KEY_FILE_NONE, NULL))
    {
        g_warning("[load]Can't read config file: %s", strFile);
        g_key_file_free(keyfile);
        return;
    }
    
    /* check [common] group */
    if (!g_key_file_has_group(keyfile, CFG_GROUPS))
    {
        g_warning("[load]Config file Error, lost [common] group in [%s]", strFile);
        g_key_file_free(keyfile);
        return;
    }
    /* get compare_edt */
    strtmp = g_key_file_get_string(keyfile, CFG_GROUPS, "compare_edt", NULL);
    if (NULL != strtmp)
    {
        len = strlen(strtmp);
        pInfo->compare_edt = (gchar*)g_malloc(len+1);
        memset(pInfo->compare_edt, 0, len + 1);
        strncpy(pInfo->compare_edt, strtmp, len);
        pInfo->compare_edt[len] = '\0';
    }
    /* get three_way_compare_edt */
    strtmp = g_key_file_get_string(keyfile, CFG_GROUPS, "three_way_compare_edt", NULL);
    if (NULL != strtmp)
    {
        len = strlen(strtmp);
        pInfo->three_way_compare_edt = (gchar*)g_malloc(len+1);
        memset(pInfo->three_way_compare_edt, 0, len + 1);
        strncpy(pInfo->three_way_compare_edt, strtmp, len);
        pInfo->three_way_compare_edt[len] = '\0';
    }
    /* get keep_files_check */
    pInfo->keep_files_check             = (gint)g_key_file_get_boolean(keyfile, CFG_GROUPS, "keep_files_check", NULL);
    /* get select_left_check */
    pInfo->select_left_check            = (gint)g_key_file_get_boolean(keyfile, CFG_GROUPS, "select_left_check", NULL);
    /* get compare_to_left_check */
    pInfo->compare_to_left_check        = (gint)g_key_file_get_boolean(keyfile, CFG_GROUPS, "compare_to_left_check", NULL);
    /* get compare_two_items_check */
    pInfo->compare_two_items_check      = (gint)g_key_file_get_boolean(keyfile, CFG_GROUPS, "compare_two_items_check", NULL);
    /* get select_to_middle_check */
    pInfo->select_to_middle_check       = (gint)g_key_file_get_boolean(keyfile, CFG_GROUPS, "select_to_middle_check", NULL);
    /* get merge_to_left_middle_check */
    pInfo->merge_to_left_middle_check   = (gint)g_key_file_get_boolean(keyfile, CFG_GROUPS, "merge_to_left_middle_check", NULL);
    /* get merge_three_items_check */
    pInfo->merge_three_items_check      = (gint)g_key_file_get_boolean(keyfile, CFG_GROUPS, "merge_three_items_check", NULL);

    /* get select_left_item_type */
    pInfo->select_left_item_type        = (gint)g_key_file_get_integer(keyfile, CFG_GROUPS, "select_left_item_type", NULL);
    /* get select_middle_item_type */
    pInfo->select_middle_item_type      = (gint)g_key_file_get_integer(keyfile, CFG_GROUPS, "select_middle_item_type", NULL);
    /* get select_left_item */
    if (0 != pInfo->select_left_item_type)
    {
        strtmp = g_key_file_get_string(keyfile, CFG_GROUPS, "select_left_item", NULL);
        if (NULL != strtmp)
        {
            len = strlen(strtmp);
            pInfo->select_left_item = (gchar*)g_malloc(len+1);
            memset(pInfo->select_left_item, 0, len + 1);
            strncpy(pInfo->select_left_item, strtmp, len);
            pInfo->select_left_item[len] = '\0';
        }
    }
    /* get select_middle_item */
    if (0 != pInfo->select_middle_item_type)
    {
        strtmp = g_key_file_get_string(keyfile, CFG_GROUPS, "select_middle_item", NULL);
        if (NULL != strtmp)
        {
            len = strlen(strtmp);
            pInfo->select_middle_item = (gchar*)g_malloc(len+1);
            memset(pInfo->select_middle_item, 0, len + 1);
            strncpy(pInfo->select_middle_item, strtmp, len);
            pInfo->select_middle_item[len] = '\0';
        }
    }
    
    return;
}

static gboolean recursion_create_folders(const char *strFolders)
{
    int status, i, len;
    gchar strBuff[PATH_MAX];
    
    /* copy folder name */
    strncpy(strBuff, strFolders, PATH_MAX - 1);
    strBuff[PATH_MAX-1] = '\0';
    
    len = strlen(strBuff);
    
#if 0
    /* append a folder sep at string end. */
    if (strBuff[len-1]!='/')
    {
        strBuff[len-1] = '/';
        strBuff[len]   = '\0';
        len++;
    }
#endif

    /* we think the root folder don't need test */
    for( i = 1; i < len; i++)
    {
        /* if it is folder sep */
        if (strBuff[i] == '/')
        {
            strBuff[i] = '\0';
            /* test folder is exist */
            status = g_access(strBuff, 0);
            if (0 != status)
            {
                status = mkdir(strBuff, S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH);
                if (0 != status)
                {
                    g_warning("[save]create folder fail![%s]", strBuff);
                    return FALSE;
                }
            }
            strBuff[i] = '/';
        }
    }
    
    return TRUE;
}

void save_perf_config_info(const PerferenceInfo *pInfo, const gchar* str_perf_file)
{
    gint len = 0;
    gchar *strtmp = NULL;
    FILE *cfg_file = NULL;
    GKeyFile * keyfile = NULL;
    gchar strFile[PATH_MAX] = {0};

    /* get folder name */
    get_xdg_home_dir(strFile);
    len = strlen(strFile);
    if (strFile[len-1] != '/')
    {
        if (len == PATH_MAX - 1)
        {
            g_warning("[save]XDG_CONFIG_HOME is too long!");
            return;
        }
        
        strFile[len-1] = '/';
        strFile[len] = '\0';
        len++;
    }

    /* create multi-parent folders */
    if (FALSE == recursion_create_folders(strFile))
    {
        return;
    }
    
    /* append file name, security issue. */
    strncpy(strFile + len, str_perf_file, (PATH_MAX - len) - 1);

    /* read/write config info */
    keyfile = g_key_file_new();

    /* file is exist? */
    if (0 == g_access(strFile,  R_OK))
    {
        if (!g_key_file_load_from_file(keyfile, strFile, G_KEY_FILE_KEEP_COMMENTS, NULL))
        {
            g_warning("[save]Can't read config file: %s", strFile);
            g_key_file_free(keyfile);
            return;
        }
    }
    else
    {
        g_warning("[save]create config file: %s", strFile);
    }
    
#ifdef G_ENABLE_DEBUG
    g_message ("compare_edt: %s", pInfo->compare_edt);
    g_message ("three_way_compare_edt: %s", pInfo->three_way_compare_edt);
#endif

    /* set compare_edt */
    if (NULL == pInfo->compare_edt)
        g_key_file_set_string(keyfile, CFG_GROUPS, "compare_edt", "");
    else
        g_key_file_set_string(keyfile, CFG_GROUPS, "compare_edt", pInfo->compare_edt);
    /* set three_way_compare_edt */
    if (NULL == pInfo->three_way_compare_edt)
        g_key_file_set_string(keyfile, CFG_GROUPS, "three_way_compare_edt", "");
    else
        g_key_file_set_string(keyfile, CFG_GROUPS, "three_way_compare_edt", pInfo->three_way_compare_edt);
    /* set keep_files_check */
    g_key_file_set_boolean(keyfile, CFG_GROUPS, "keep_files_check", pInfo->keep_files_check);
    /* set select_left_check */
    g_key_file_set_boolean(keyfile, CFG_GROUPS, "select_left_check", pInfo->select_left_check);
    /* set compare_to_left_check */
    g_key_file_set_boolean(keyfile, CFG_GROUPS, "compare_to_left_check", pInfo->compare_to_left_check);
    /* set compare_two_items_check */
    g_key_file_set_boolean(keyfile, CFG_GROUPS, "compare_two_items_check", pInfo->compare_two_items_check);
    /* set select_to_middle_check */
    g_key_file_set_boolean(keyfile, CFG_GROUPS, "select_to_middle_check", pInfo->select_to_middle_check);
    /* set merge_to_left_middle_check */
    g_key_file_set_boolean(keyfile, CFG_GROUPS, "merge_to_left_middle_check", pInfo->merge_to_left_middle_check);
    /* set merge_three_items_check */
    g_key_file_set_boolean(keyfile, CFG_GROUPS, "merge_three_items_check", pInfo->merge_three_items_check);
    /* set select_left_item_type */
    g_key_file_set_integer(keyfile, CFG_GROUPS, "select_left_item_type", pInfo->select_left_item_type);
    /* set select_middle_item_type */
    g_key_file_set_integer(keyfile, CFG_GROUPS, "select_middle_item_type", pInfo->select_middle_item_type);
    /* set select_left_item */
    if (NULL == pInfo->select_left_item)
        g_key_file_set_string(keyfile, CFG_GROUPS, "select_left_item", "");
    else
        g_key_file_set_string(keyfile, CFG_GROUPS, "select_left_item", pInfo->select_left_item);
    /* set select_middle_item */
    if (NULL == pInfo->select_middle_item)
        g_key_file_set_string(keyfile, CFG_GROUPS, "select_middle_item", "");
    else
        g_key_file_set_string(keyfile, CFG_GROUPS, "select_middle_item", pInfo->select_middle_item);

    /* open config file in write mode */
    cfg_file = fopen(strFile, "w");
    if (NULL == cfg_file)
    {
        g_warning("[save]Can't write config file: %s", strFile);
        g_key_file_free(keyfile);
        return;
    }

    /* get key file data */
    len = 0;
    strtmp = g_key_file_to_data(keyfile, (gsize*)&len, NULL);
    g_key_file_free(keyfile);
    
    /* write to file */
    if (fwrite(strtmp, 1, len, cfg_file) != len)
    {
        g_warning("[save]failed in write config file: %s", strFile);
    }

    /* free this memory */
    g_free(strtmp);

    /* close file handle */
    fclose(cfg_file);

#ifdef G_ENABLE_DEBUG
    g_message ("save config file finish");
#endif

    return;
}

static void info_to_dlg_ddx(const PerferenceInfo *pInfo, PerferenceDlg *pDlg)
{
#ifdef G_ENABLE_DEBUG
    g_message ("init cmp_edt: %s", pInfo->compare_edt);
#endif
    
    if (NULL != pInfo->compare_edt)
        gtk_entry_set_text (GTK_ENTRY (pDlg->compare_edt), pInfo->compare_edt);
    if (NULL != pInfo->three_way_compare_edt)
        gtk_entry_set_text (GTK_ENTRY (pDlg->three_way_compare_edt), pInfo->three_way_compare_edt);
    if (0 != pInfo->keep_files_check)
        gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (pDlg->keep_files_check), pInfo->keep_files_check);
    if (0 != pInfo->select_left_check)
        gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (pDlg->select_left_check), pInfo->select_left_check);
    if (0 != pInfo->compare_to_left_check)
        gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (pDlg->compare_to_left_check), pInfo->compare_to_left_check);
    if (0 != pInfo->compare_two_items_check)
        gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (pDlg->compare_two_items_check), pInfo->compare_two_items_check);
    if (0 != pInfo->select_to_middle_check)
        gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (pDlg->select_to_middle_check), pInfo->select_to_middle_check);
    if (0 != pInfo->select_two_item_to_merge_check)
        gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (pDlg->select_two_item_to_merge_check), pInfo->select_two_item_to_merge_check);
    if (0 != pInfo->merge_to_left_check)
        gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (pDlg->merge_to_left_check), pInfo->merge_to_left_check);
    if (0 != pInfo->merge_to_left_middle_check)
        gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (pDlg->merge_to_left_middle_check), pInfo->merge_to_left_middle_check);
    if (0 != pInfo->merge_three_items_check)
        gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (pDlg->merge_three_items_check), pInfo->merge_three_items_check);
}

static void dlg_to_info_ddx(const PerferenceDlg *pDlg, PerferenceInfo *pInfo)
{
    guint len;
    gchar* dest_info;
    const gchar* src_info;

    if (NULL != pInfo->compare_edt)
        g_free(pInfo->compare_edt);
    if (NULL != pInfo->three_way_compare_edt)
        g_free(pInfo->three_way_compare_edt);
    pInfo->compare_edt = NULL;
    pInfo->three_way_compare_edt = NULL;

    src_info = gtk_entry_get_text (GTK_ENTRY (pDlg->compare_edt));
    len = strlen(src_info);
    if (0 != len)
    {
        dest_info = (gchar*)g_malloc(len+1);
        memset(dest_info, 0, len + 1);
        strncpy(dest_info, src_info, len);
        pInfo->compare_edt = dest_info;
    }
    src_info = gtk_entry_get_text (GTK_ENTRY (pDlg->three_way_compare_edt));
    len = strlen(src_info);
    if (0 != len)
    {
        dest_info = (gchar*)g_malloc(len+1);
        memset(dest_info, 0, len + 1);
        strncpy(dest_info, src_info, len);
        pInfo->three_way_compare_edt = dest_info;
    }

    pInfo->keep_files_check                 = (int)gtk_toggle_button_get_active (GTK_TOGGLE_BUTTON (pDlg->keep_files_check));
    pInfo->select_left_check                = (int)gtk_toggle_button_get_active (GTK_TOGGLE_BUTTON (pDlg->select_left_check));
    pInfo->compare_to_left_check            = (int)gtk_toggle_button_get_active (GTK_TOGGLE_BUTTON (pDlg->compare_to_left_check));
    pInfo->compare_two_items_check          = (int)gtk_toggle_button_get_active (GTK_TOGGLE_BUTTON (pDlg->compare_two_items_check));
    pInfo->select_to_middle_check           = (int)gtk_toggle_button_get_active (GTK_TOGGLE_BUTTON (pDlg->select_to_middle_check));
    pInfo->select_two_item_to_merge_check   = (int)gtk_toggle_button_get_active (GTK_TOGGLE_BUTTON (pDlg->select_two_item_to_merge_check));
    pInfo->merge_to_left_check              = (int)gtk_toggle_button_get_active (GTK_TOGGLE_BUTTON (pDlg->merge_to_left_check));
    pInfo->merge_to_left_middle_check       = (int)gtk_toggle_button_get_active (GTK_TOGGLE_BUTTON (pDlg->merge_to_left_middle_check));
    pInfo->merge_three_items_check          = (int)gtk_toggle_button_get_active (GTK_TOGGLE_BUTTON (pDlg->merge_three_items_check));
}

static void on_cancel_btn_clicked(const PerferenceDlg *pDlg, GtkButton *button)
{
    gtk_dialog_response( GTK_DIALOG(pDlg->pDialog) , GTK_RESPONSE_CANCEL);
#ifdef G_ENABLE_DEBUG
    g_message ("cancel exit");
#endif
}

static void on_ok_btn_clicked(const PerferenceDlg *pDlg, GtkButton *button)
{
    dlg_to_info_ddx(pDlg, pDlg->pstInfo);
    gtk_dialog_response( GTK_DIALOG(pDlg->pDialog) , GTK_RESPONSE_OK);
    
#ifdef G_ENABLE_DEBUG
    g_message ("ok exit");
#endif
}

static void on_apply_btn_clicked(const PerferenceDlg *pDlg, GtkButton *button)
{
    dlg_to_info_ddx(pDlg, pDlg->pstInfo);
}

static void on_browse_clicked(GtkWidget *result_edt, GtkButton *button)
{
    GtkWidget *dialog;
    GtkResponseType response;
    GtkFileFilter* file_filter;
    GtkWindow *parent_window = (GtkWindow*)gtk_widget_get_parent((GtkWidget*)button);

    dialog = gtk_file_chooser_dialog_new (_("Open File"), parent_window, 
                GTK_FILE_CHOOSER_ACTION_OPEN, GTK_STOCK_CANCEL, GTK_RESPONSE_CANCEL,
                GTK_STOCK_OPEN, GTK_RESPONSE_ACCEPT, NULL);

    file_filter = gtk_file_filter_new();
    gtk_file_filter_add_mime_type(file_filter, "application/x-executable");
    //gtk_file_filter_add_mime_type(file_filter, "application/x-desktop");
    gtk_file_filter_set_name(file_filter, _("application file"));
    gtk_file_chooser_add_filter(GTK_FILE_CHOOSER (dialog), file_filter);

    response = gtk_dialog_run (GTK_DIALOG (dialog));
    if ( (GTK_RESPONSE_YES == response) || (GTK_RESPONSE_OK == response) || (GTK_RESPONSE_ACCEPT == response))
    {
         char *filename;
         filename = gtk_file_chooser_get_filename (GTK_FILE_CHOOSER (dialog));
         gtk_entry_set_text (GTK_ENTRY (result_edt), filename);
         g_free (filename);
    }
    gtk_widget_destroy (dialog);
}

GtkWidget* create_edit_perf_win (GtkWindow *parent, PerferenceDlg *pDlg, PerferenceInfo *pInfo)
{
  GtkWidget *edit_perf_win;
  GtkWidget *vbox1;
  GtkWidget *vbox2;
  GtkWidget *hbox1;
  GtkWidget *compare_label;
  GtkWidget *alignment3;
  GtkWidget *btn_browse_compare;
  GtkWidget *compare_edt;
  GtkWidget *hbox2;
  GtkWidget *label1;
  GtkWidget *alignment4;
  GtkWidget *btn_browse_3_way_compare;
  GtkWidget *three_way_compare_edt;
  GtkWidget *alignment2;
  GtkWidget *keep_files_check;
  GtkWidget *hseparator2;
  GtkWidget *select_left_check;
  GtkWidget *compare_to_left_check;
  GtkWidget *compare_two_items_check;
  GtkWidget *select_to_middle_check;
  GtkWidget *select_two_item_to_merge_check;
  GtkWidget *merge_to_left_check;
  GtkWidget *merge_to_left_middle_check;
  GtkWidget *merge_three_items_check;
  GtkWidget *hbuttonbox1;
  GtkWidget *ok_btn;
  GtkWidget *cancel_btn;
  GtkWidget *apply_btn;
  GtkWidget *hseparator1;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

#if 0
  edit_perf_win = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (edit_perf_win), 5);
  gtk_window_set_title (GTK_WINDOW (edit_perf_win), _("Setup diff plugin perferences"));
  gtk_window_set_position (GTK_WINDOW (edit_perf_win), GTK_WIN_POS_CENTER);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (edit_perf_win), TRUE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (edit_perf_win), vbox1);
#else
  GtkWidget *content_area;
  
  edit_perf_win = gtk_dialog_new_with_buttons (_("Setup diff plugin perferences"), 
                          parent, GTK_DIALOG_MODAL | GTK_DIALOG_DESTROY_WITH_PARENT, NULL);
                          
  content_area = gtk_dialog_get_content_area (GTK_DIALOG (edit_perf_win));
  gtk_container_set_border_width (GTK_CONTAINER (content_area), 5);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (content_area), vbox1);
#endif

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox2, TRUE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox1, FALSE, TRUE, 0);

  compare_label = gtk_label_new (_("compare command:      "));
  gtk_widget_show (compare_label);
  gtk_box_pack_start (GTK_BOX (hbox1), compare_label, FALSE, FALSE, 0);

  alignment3 = gtk_alignment_new (1, 0.5, 0.2, 1);
  gtk_widget_show (alignment3);
  gtk_box_pack_start (GTK_BOX (hbox1), alignment3, TRUE, TRUE, 0);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment3), 2, 2, 20, 2);

  btn_browse_compare = gtk_button_new_with_mnemonic (_("browse"));
  gtk_widget_show (btn_browse_compare);
  gtk_container_add (GTK_CONTAINER (alignment3), btn_browse_compare);

  compare_edt = gtk_entry_new ();
  gtk_widget_show (compare_edt);
  gtk_box_pack_start (GTK_BOX (vbox2), compare_edt, FALSE, FALSE, 2);
  gtk_entry_set_invisible_char (GTK_ENTRY (compare_edt), 9679);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox2, FALSE, FALSE, 0);

  label1 = gtk_label_new (_("3-way compare command:"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox2), label1, FALSE, FALSE, 0);

  alignment4 = gtk_alignment_new (1, 0.5, 0.2, 1);
  gtk_widget_show (alignment4);
  gtk_box_pack_start (GTK_BOX (hbox2), alignment4, TRUE, TRUE, 0);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment4), 2, 2, 20, 2);

  btn_browse_3_way_compare = gtk_button_new_with_mnemonic (_("browse"));
  gtk_widget_show (btn_browse_3_way_compare);
  gtk_container_add (GTK_CONTAINER (alignment4), btn_browse_3_way_compare);

  three_way_compare_edt = gtk_entry_new ();
  gtk_widget_show (three_way_compare_edt);
  gtk_box_pack_start (GTK_BOX (vbox2), three_way_compare_edt, FALSE, FALSE, 2);
  gtk_entry_set_invisible_char (GTK_ENTRY (three_way_compare_edt), 9679);

  alignment2 = gtk_alignment_new (0, 0.5, 0, 1);
  gtk_widget_show (alignment2);
  gtk_box_pack_start (GTK_BOX (vbox2), alignment2, FALSE, TRUE, 0);

  keep_files_check = gtk_check_button_new_with_mnemonic (_("_Keep files in config file after comparison"));
  gtk_widget_show (keep_files_check);
  gtk_container_add (GTK_CONTAINER (alignment2), keep_files_check);
  gtk_tooltips_set_tip (tooltips, keep_files_check, _("Keep files in config file after comparison"), NULL);
  gtk_widget_add_accelerator (keep_files_check, "activate", accel_group,
                              GDK_3, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (keep_files_check, "activate", accel_group,
                              GDK_3, (GdkModifierType) GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator2, FALSE, TRUE, 0);

  select_left_check = gtk_check_button_new_with_mnemonic (_("Display [Select as left] in content menu"));
  gtk_widget_show (select_left_check);
  gtk_box_pack_start (GTK_BOX (vbox2), select_left_check, FALSE, FALSE, 0);

  compare_to_left_check = gtk_check_button_new_with_mnemonic (_("Display [Compare To:] in content menu"));
  gtk_widget_show (compare_to_left_check);
  gtk_box_pack_start (GTK_BOX (vbox2), compare_to_left_check, FALSE, FALSE, 0);

  compare_two_items_check = gtk_check_button_new_with_mnemonic (_("Display [Compare Two Items] in content menu"));
  gtk_widget_show (compare_two_items_check);
  gtk_box_pack_start (GTK_BOX (vbox2), compare_two_items_check, FALSE, FALSE, 0);

  select_to_middle_check = gtk_check_button_new_with_mnemonic (_("Display [Select as middle] in content menu"));
  gtk_widget_show (select_to_middle_check);
  gtk_box_pack_start (GTK_BOX (vbox2), select_to_middle_check, FALSE, FALSE, 0);
  
  select_two_item_to_merge_check = gtk_check_button_new_with_mnemonic (_("Display [Select Two Items as Left&Middle] in content menu"));
  gtk_widget_show (select_two_item_to_merge_check);
  gtk_box_pack_start (GTK_BOX (vbox2), select_two_item_to_merge_check, FALSE, FALSE, 0);

  merge_to_left_check = gtk_check_button_new_with_mnemonic (_("Display [Merge to Left] in content menu"));
  gtk_widget_show (merge_to_left_check);
  gtk_box_pack_start (GTK_BOX (vbox2), merge_to_left_check, FALSE, FALSE, 0);

  merge_to_left_middle_check = gtk_check_button_new_with_mnemonic (_("Display [Merge To Left&Middle] in content menu"));
  gtk_widget_show (merge_to_left_middle_check);
  gtk_box_pack_start (GTK_BOX (vbox2), merge_to_left_middle_check, FALSE, FALSE, 0);

  merge_three_items_check = gtk_check_button_new_with_mnemonic (_("Display [Merge Three Items] in content menu"));
  gtk_widget_show (merge_three_items_check);
  gtk_box_pack_start (GTK_BOX (vbox2), merge_three_items_check, FALSE, FALSE, 0);

#if 0
  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_end (GTK_BOX (vbox1), hbuttonbox1, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox1), 11);
#else
  hbuttonbox1 = gtk_dialog_get_action_area(GTK_DIALOG (edit_perf_win));
#endif

  ok_btn = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (ok_btn);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), ok_btn);
  GTK_WIDGET_SET_FLAGS (ok_btn, GTK_CAN_DEFAULT);

  cancel_btn = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancel_btn);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), cancel_btn);
  GTK_WIDGET_SET_FLAGS (cancel_btn, GTK_CAN_DEFAULT);

  apply_btn = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_show (apply_btn);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), apply_btn);
  GTK_WIDGET_SET_FLAGS (apply_btn, GTK_CAN_DEFAULT);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator1, FALSE, TRUE, 5);

    pDlg->compare_edt                   = compare_edt;
    pDlg->three_way_compare_edt         = three_way_compare_edt;
    pDlg->keep_files_check              = keep_files_check;
    pDlg->select_left_check             = select_left_check;
    pDlg->compare_to_left_check         = compare_to_left_check;
    pDlg->compare_two_items_check       = compare_two_items_check;
    pDlg->select_to_middle_check        = select_to_middle_check;
    pDlg->select_two_item_to_merge_check= select_two_item_to_merge_check;
    pDlg->merge_to_left_check           = merge_to_left_check;
    pDlg->merge_to_left_middle_check    = merge_to_left_middle_check;
    pDlg->merge_three_items_check       = merge_three_items_check;
    info_to_dlg_ddx(pInfo, pDlg);
    pDlg->pstInfo                       = pInfo;
    pDlg->pDialog                       = edit_perf_win;

#if 0
  g_signal_connect_swapped ((gpointer) edit_perf_win, "delete_event",
                            G_CALLBACK (gtk_main_quit),
                            NULL);
#endif
  g_signal_connect_swapped ((gpointer) cancel_btn, "clicked",
                            G_CALLBACK (on_cancel_btn_clicked),
                            GTK_OBJECT (pDlg));

  g_signal_connect_swapped ((gpointer) btn_browse_compare, "clicked",
                            G_CALLBACK (on_browse_clicked),
                            GTK_OBJECT (compare_edt));
  g_signal_connect_swapped ((gpointer) btn_browse_3_way_compare, "clicked",
                            G_CALLBACK (on_browse_clicked),
                            GTK_OBJECT (three_way_compare_edt));

  g_signal_connect_swapped ((gpointer) ok_btn, "clicked",
                            G_CALLBACK (on_ok_btn_clicked),
                            GTK_OBJECT (pDlg));
  g_signal_connect_swapped ((gpointer) apply_btn, "clicked",
                            G_CALLBACK (on_apply_btn_clicked),
                            GTK_OBJECT (pDlg));

  gtk_widget_grab_default (ok_btn);
  gtk_window_add_accel_group (GTK_WINDOW (edit_perf_win), accel_group);

  return edit_perf_win;
}

